version: "3"
services:
    weblogic:
        image: container-registry.oracle.com/middleware/weblogic:12.2.1.3 #weblogic:12.2.1.3-dev #12.2.1.3-dev #14.1.1.0-dev-8
        container_name: AdminServer
        deploy:
            resources:
                limits:
                    memory: 1GB
        environment:
            ADMINISTRATION_PORT_ENABLED: false
            DOMAIN_NAME: mydomain
            DEBUG_FLAG: true
            DEBUG_PORT: 4000
            PRODUCTION_MODE: dev
            JAVA_OPTIONS: -Xdebug -Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=n -Dfile.encoding=UTF8
            TZ: America/Sao_Paulo
        ports:
            - "7001:7001"
            - "4000:4000"
        volumes:
            - "./properties:/u01/oracle/properties"
       